### ISSUE TITLE
HttpClient.getBlobAsync lacks support for IE versions < 79

### ISSUE THREAD

**Issue by hgut-eq** [equinor/fusion-api#180]
`getBlobAsync` returns a [File ](url)and not a [Blob](url), which means that the function will crash when run in a IE browser with version less than 79 (see https://developer.mozilla.org/en-US/docs/Web/API/File#Browser_compatibility).

Proposing one of the following solutions:

1. Changing the interface of `getBlobAsync `to return e.g. `{ blob, fileName }` instead of `File`. Proposing inclusion of `fileName `as well, since the caller won't be able to resolve this on its own.
     Should probably also create a new `getFileAsync `that can be used instead of the previous `getBlobAsync `implementation. These two new functions will have a more intuitive and correct name according to their return type

2. Create a new function, e.g. `getIEBlobAsync`, that returns `{ blob, fileName }` instead of `File`. Not the most elegent approach, but it allows `getBlobAsync `to remain intact for any potential existing users

**Comment by MartinForre** [comment]
I support solution nr 1 👍
